#!/usr/bin/env make -f
# author: amoblin <amoblin@gmail.com>
# file name: Makefile
# description: TODO
# create date: 2014-11-03
# This file is created from $MARBOO_HOME/media/starts/Makefile
# 本文件由 $MARBOO_HOME/media/starts/Makefile　复制而来

default:
	aglio -t templates/default.jade -i api.apib -o ../api.html

demo:
	aglio -t templates/default.jade -i example-cn.apib -o example-cn.html
